### ISSUE TITLE
Error "Could not load collection." at pidgin launch.

### ISSUE THREAD

**Issue by Cbhihe** [GRBurst/purple-gnome-keyring#7]
Hi, just installed 'pidgin', 'purple-plugin-pack', 'purple-skype-web', 'pidgin-ib-notify', etc...

Also installed Purple Hangouts, Purple Telegram, and purple-gnome-keyring from AUR.

All is well except that, everytime I launch pidgin, I get a small window with the follwoing message: "Gnome Keyring Plugin could not load collection" with a close button. 
I am new as much to Pidgin as to how exactly Gnome Keyring works so maybe my question is not pertinent. Can you give me pointers so I can start troubleshooting this ? 
Thanks. -ced

**Comment by GRBurst** [comment]
@Cbhihe sry for the late response. Do you have any keyring? Best way to check that is to install seahorse (gui for the gnome keyring), start it see if there is anything in the "Passwords" area.

**Comment by Cbhihe** [comment]
No need to apologize, GRBurst. We all have a life after all, and I am grateful for your response. So 12 days later, I come to and continue this. 
Yes, I do have 'seahorse' installed on my OS [4.13.9-1-ARCH  with gnome running gdm on xorg].
The default keyring is "login" and it is automatically unlocked when I login either at console or from gdm. 
I went back to the plugin menu in Pidgin > Tools > Plugins > Gnome Keyring Plugin 1.1.3 and realized that I had selected "custom keyring" and specified one. I unselected that so the plugin can use the system default, and the "load keyring" error disappeared. 
So this may not be a bug at all (sorry for the scare if scare there was, which I doubt  ;-)  ).

I guess the question becomes how does one use a custom keyring with Pidgin? Should it be first created in Seahorse or from cli ? , then populated outside Pidgin with whatever Pidgin accounts one may have ? Can one use simultaneously a custom keyring for certain pidgin accounts (as specified in the plugin config window) AND the standard system keyring for other pidgin accounts ?
Cheers,  -ced

**Comment by GRBurst** [comment]
Hey I will close that issue.
I would advise to use the `secret-tool` command line tool since it offers the option to use key-value pairs in order to store and receive items from your keyring. 
And again - sry for the delay. Currently it is hard for me to find some free time :-(
